#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete citrack.@freifunk_p2pblock[-1]
	add ucitrack freifunk_p2pblock
	set ucitrack.@freifunk_p2pblock[-1].init=freifunk-p2pblock
	commit ucitrack
EOF

/etc/init.d/freifunk-p2pblock enabled && {
	/etc/init.d/freifunk-p2pblock stop
	/etc/init.d/freifunk-p2pblock disable
}

rm -f /tmp/luci-indexcache
exit 0
