var cgi_url="/cgi-bin/vizdata.sh",maxmetric=3,iconvariant="-mini",nodes=[],ncount=0,newnodes=[],edges=[],iel=220,optsize=10,vwidth=0,vheight=0,xoff=0,yoff=0,scale=1,idle_timeout=15,erase_timeout=60,dcl_timeout=250,dcllow_timeout=500,auto_declump=!0,showdesc=!0,auto_save=1,now_secs=5,IFrameObj,maindiv,nodediv,edgediv;
function callToServer(a){var b;if(IFrameObj.document)b=IFrameObj.document;else if(IFrameObj.contentDocument)b=IFrameObj.contentDocument;else if(IFrameObj.contentWindow)b=IFrameObj.contentWindow.document;else return!0;b.location.replace(a);return!1}
function edge(a,b){this.getHTML=function(){var a="";if(this.n1.metric>maxmetric||this.n2.metric>maxmetric)return"";x=this.n1.x*scale;y=this.n1.y*scale;dx=this.n2.x*scale-x;dy=this.n2.y*scale-y;x+=xoff*scale+75;y+=yoff*scale+15;imgtag="<img src='/luci-static/resources/olsr-viz/dot_";imgtag=0<this.etx&&2>this.etx?imgtag+"good.gif'":2<this.etx&&5>this.etx?imgtag+"ok.gif'":5<this.etx&&10>this.etx?imgtag+"weak.gif'":imgtag+"down.gif'";imgtag+=" alt='ETX: "+this.etx+"' title='ETX: "+this.etx+"' ";d=Math.sqrt(dx*
dx+dy*dy);for(j=0;j<d;j+=15)a+=imgtag+"style='top:"+parseInt(y+dy*j/d)+"px; left:"+parseInt(x+dx*j/d)+"px; width: 4px; height: 4px; position: absolute; z-index: 2' >";return a+="<div style='top:"+parseInt(y+0.5*dy-5)+"px; left:"+parseInt(x+0.5*dx-24)+"px; position: absolute; z-index: 3; width: 48px; text-align: center;' ><span class='label etx' >"+this.etx+"</span></div>"};this.isIdle=function(){return now_secs-this.lastseen>idle_timeout};this.isDead=function(){return now_secs-this.lastseen>erase_timeout};
this.cleanup=function(){this.n1&&this.n1.weight&&this.n1.weight--;this.n2&&this.n2.weight&&this.n2.weight--;this.n1&&this.n2&&(delete this.n1.edges[b.ip],delete this.n2.edges[a.ip])};this.n1=a;this.n2=b;this.n1.weight++;this.n1.edges[b.ip]=this;this.n2.weight++;this.n2.edges[a.ip]=this;return this}function getEdgeKey(a,b){key="";return key=a>b?b+"-"+a:a+"-"+b}function touch_edge(a,b,f){var k=getEdgeKey(a.ip,b.ip),g=edges[k];g||(g=new edge(a,b),edges[k]=g);g.etx=f;g.lastseen=now_secs;return g}
function node(a){this.getHTML=function(){if(this.metric>maxmetric)return"";var a=0;for(h in this.hna)if("0.0.0.0"==h){a=1;break}return"<div id='node_"+this.ip+"' onmousedown='dragstart(this)' style='top: "+parseInt((this.y+yoff)*scale)+"px; left: "+parseInt((this.x+xoff)*scale)+"px; width: 150px; height: 1px; z-index: 4; position: absolute; background-color: transparent;' ><div><img src='/luci-static/resources/olsr-viz/node"+(a?"-hna":"")+iconvariant+".gif' alt='node "+this.ip+"' style='border: none;'><br><a href='http://"+
this.ip+"/'><span class='label ip'>"+this.ip+"</span></a>"+(showdesc&&""!=this.desc?"<br><span class='label desc'>"+this.desc+"</span>":"")+"</div></div>"};this.isIdle=function(){return now_secs-this.lastseen>idle_timeout};this.isDead=function(){return now_secs-this.lastseen>erase_timeout};this.cleanup=function(){ncount--};this.set_metric=function(a){this.metric=a;return this};this.set_desc=function(a){this.desc=a;return this};this.update=function(){this.lastseen=now_secs;return this};this.ip=a;this.dy_last=
this.dx_last=this.y=this.x=0;this.placed=!1;this.weight=0;this.edges=[];this.hna=[];this.pinned=!1;this.metric=999;this.desc="";ncount++;return this}function touch_node(a){n=nodes[a];n||(n=new node(a),nodes[a]=n,newnodes[newnodes.length]=n);return n}
function place_new_nodes(){var a=0;for(i=0;i<newnodes.length;i++)if(n=newnodes[i],!n.placed){if(sp=getCookie("node_"+n.ip))xy=sp.split("x"),debug_writeln("sp: "+sp+" xy[0]: "+xy[0]+" xy[1]: "+xy[1]),n.x=parseFloat(xy[0]),n.y=parseFloat(xy[1]);else if(1<n.weight){c=dy=dx=oy=ox=0;for(e in n.edges)nodes[e]&&nodes[e].placed&&(!ox&&!oy?(ox=nodes[e].x,oy=nodes[e].y):(dx+=nodes[e].x-ox,dy+=nodes[e].y-oy),c++);0<c&&(n.x=ox+dx/c+Math.random()*iel/2-iel/4,n.y=oy+dy/c+Math.random()*iel/2-iel/4)}else n.x=400*
Math.random(),n.y=400*Math.random();n.placed=!0;a++}newnodes.length=0;return a}function hna(a,b,f){this.gw=a;this.net=b;this.mask=f;return this}function touch_hna(a,b,f){h=a.hna[b];h||(h=new hna(a.ip,b,f),a.hna[b]=h);h.lastseen=now_secs;return h}
function viz_setup(a,b,f,k){IFrameObj=document.getElementById(a);document.frames&&(IFrameObj=document.frames[a]);draginit();maindiv=document.getElementById(b);nodediv=document.getElementById(f);edgediv=document.getElementById(k);if(autosave=getCookie("prefs_autosave"))auto_save=parseInt(autosave);viz_autosave(auto_save);(mmx=getCookie("prefs_maxmetric"))&&set_maxmetric(mmx,!0,!0);(savescale=getCookie("prefs_scale"))&&(savescale=parseFloat(savescale))&&set_scale(savescale,!0)}
function viz_save(){exp=new Date;exp.setTime(exp.getTime()+2592E6);for(ip in nodes)nodes[ip].metric>maxmetric||setCookie("node_"+ip,nodes[ip].x+"x"+nodes[ip].y,exp);setCookie("prefs_maxmetric",maxmetric,exp);setCookie("prefs_scale",scale,exp);setCookie("prefs_innerview",parseInt(maindiv.scrollLeft)+"x"+parseInt(maindiv.scrollTop)+"x"+parseInt(vwidth*scale)+"x"+parseInt(vheight*scale),exp)}function viz_autosave(a){(auto_save=a)?document.body.onunload=viz_save:deleteCookie("prefs_autosave")}
function viz_reset(){deleteAllCookies();for(ip in nodes)delete nodes[ip];for(e in edges)delete edges[e];viz_update()}var updateTimer=0;function viz_update(){updateTimer&&clearTimeout(updateTimer);now_secs=(new Date).getTime()/1E3;callToServer(cgi_url)}function viz_callback(){updateTimer&&clearTimeout(updateTimer);0<place_new_nodes()&&auto_declump&&declump();refresh();updateTimer=setTimeout("viz_update()",5E3)}var refresh_running=!1;
function refresh(){if(!refresh_running){refresh_running=!0;var a="",a="",b;for(b in nodes)nodes[b].isDead()?(nodes[b].cleanup(),delete nodes[b]):a+=nodes[b].getHTML();nodediv.innerHTML=a;var a="",f;for(f in edges)edges[f].isDead()?(edges[f].cleanup(),delete edges[f]):a+=edges[f].getHTML();edgediv.innerHTML=a;refresh_running=!1}}function set_showdesc(a){showdesc=a;noupdate||refresh()}function set_autodeclump(a){(auto_declump=a)?declump():clearTimeout(dclTimer)}
function set_scale(a,b){a||(a=parseFloat(document.getElementById("zoom").value/2));scale=Math.round(100*a)/100;if(!scale||0.1>scale)scale=0.1;document.getElementById("zoom").value=2*scale;b||refresh()}function set_maxmetric(a,b,f){a=parseInt(a);if(0<a||!f||confirm("warning. setting the maximum metric to zero can lead to expensive calculations if you are connected to a network with many nodes. do you want to proceed?"))maxmetric=a;document.getElementById("maxmetric").value=maxmetric;b||refresh()}
function fr(a){return Math.pow(iel*iel/a,2)}function fa(a){return Math.pow(a*a/iel,2)}var dclTimer=0,declump_running=!1;
function declump(){dclTimer&&clearTimeout(dclTimer);if(!declump_running){declump_running=!0;nc=0;for(var a in nodes)nodes[a].fr_x=0,nodes[a].fr_y=0,nodes[a].fa_x=0,nodes[a].fa_y=0,nodes[a].x_next=nodes[a].x,nodes[a].y_next=nodes[a].y,nodes[a].randdisplace=0;for(a in nodes)if(!(nodes[a].metric>maxmetric||nodes[a].pinned)){for(ip2 in nodes)nodes[ip2].metric>maxmetric||a==ip2||(dx=nodes[a].x_next-nodes[ip2].x_next,dy=nodes[a].y_next-nodes[ip2].y_next,d=Math.sqrt(dx*dx+dy*dy),d=Math.max(d-optsize,(d+
optsize)/optsize),nodes[a].fr_x+=dx/d*fr(d),nodes[a].fr_y+=dy/d*fr(d));dx=nodes[a].fr_x;dy=nodes[a].fr_y;d=Math.sqrt(dx*dx+dy*dy);md=Math.min(d,iel/nodes[a].weight);nodes[a].x_next+=dx/d*md;nodes[a].y_next+=dy/d*md;nc++}ec=0;for(var b in edges)if(edges[b].n1&&edges[b].n2&&!(edges[b].n1.metric>maxmetric||edges[b].n2.metric>maxmetric))dx=edges[b].n1.x_next-edges[b].n2.x_next,dy=edges[b].n1.y_next-edges[b].n2.y_next,d=Math.sqrt(dx*dx+dy*dy),edges[b].n1.fa_x-=dx/d*fa(d),edges[b].n1.fa_y-=dy/d*fa(d),edges[b].n2.fa_x+=
dx/d*fa(d),edges[b].n2.fa_y+=dy/d*fa(d),ec++;ymin=xmin=-20;ymax=xmax=20;dsum=0;for(var f in nodes)nodes[f].metric>maxmetric||nodes[f].pinned||(dx=nodes[f].fa_x,dy=nodes[f].fa_y,d=Math.sqrt(dx*dx+dy*dy),dx=0.75*dx/d*Math.min(d,iel/nodes[f].weight)+0.25*nodes[f].dx_last,dy=0.75*dy/d*Math.min(d,iel/nodes[f].weight)+0.25*nodes[f].dy_last,nodes[f].dx_last=dx,nodes[f].dy_last=dy,nodes[f].x_next+=dx,nodes[f].y_next+=dy,nodes[f].x_next&&nodes[f].y_next&&(dx=nodes[f].x-nodes[f].x_next,dy=nodes[f].y-nodes[f].y_next,
dsum+=Math.sqrt(dx*dx+dy*dy),nodes[f].x=nodes[f].x_next,nodes[f].y=nodes[f].y_next,xmin=Math.min(xmin,nodes[f].x),xmax=Math.max(xmax,nodes[f].x),ymin=Math.min(ymin,nodes[f].y),ymax=Math.max(ymax,nodes[f].y)));vwidth=xmax-xmin;vheight=ymax-ymin;xoff=-xmin;yoff=-ymin;refresh();auto_declump&&(dclTimer=setTimeout("declump()",dsum>ncount?dcl_timeout:dcllow_timeout));declump_running=!1}}var dragip=null,dragx=0,dragy=0,posx=0,posy=0;
function draginit(){document.onmousemove=drag;document.onmouseup=dragstop}function dragstart(a){dragip=a.id.split("_")[1];dragx=posx-a.offsetLeft;dragy=posy-a.offsetTop;if(n=nodes[dragip])n.pinned=!0}function dragstop(){if(n=nodes[dragip])n.pinned=!1;refresh();dragip=null}
function drag(a){posx=document.all?window.event.clientX:a.pageX;posy=document.all?window.event.clientY:a.pageY;if(null!=dragip){if(n=nodes[dragip])n.x=(posx-dragx)/scale-xoff,n.y=(posy-dragy)/scale-yoff;e=document.getElementById("node_"+dragip);e.style.left=parseInt((n.x+xoff)*scale)+"px";e.style.top=parseInt((n.y+yoff)*scale)+"px"}}function debug_writeln(a){document.getElementById("debug").innerHTML=a+"<br>"+document.getElementById("debug").innerHTML}
function setCookie(a,b,f,k,g,l){document.cookie=a+"="+escape(b)+(f?"; expires="+f.toGMTString():"")+(k?"; path="+k:"")+(g?"; domain="+g:"")+(l?"; secure":"")}function getCookie(a){return(a=document.cookie.match(a+"=(.*?)(;|$)"))?unescape(a[1]):null}function deleteCookie(a,b,f){getCookie(a)&&(document.cookie=a+"="+(b?"; path="+b:"")+(f?"; domain="+f:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT")}
function deleteAllCookies(){cookies=document.cookie.split("; ");for(i=0;i<cookies.length;i++)deleteCookie(cookies[i].split("=")[0])};
