var cbi_d=[],cbi_t=[],cbi_c=[],cbi_validators={integer:function(){return null!=this.match(/^-?[0-9]+$/)},uinteger:function(){return cbi_validators.integer.apply(this)&&0<=this},"float":function(){return!isNaN(parseFloat(this))},ufloat:function(){return cbi_validators["float"].apply(this)&&0<=this},ipaddr:function(){return cbi_validators.ip4addr.apply(this)||cbi_validators.ip6addr.apply(this)},ip4addr:function(){return this.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})(\/(\S+))?$/)?0<=RegExp.$1&&
255>=RegExp.$1&&0<=RegExp.$2&&255>=RegExp.$2&&0<=RegExp.$3&&255>=RegExp.$3&&0<=RegExp.$4&&255>=RegExp.$4&&(0>RegExp.$6.indexOf(".")?0<=RegExp.$6&&32>=RegExp.$6:cbi_validators.ip4addr.apply(RegExp.$6)):!1},ip6addr:function(){if(this.match(/^([a-fA-F0-9:.]+)(\/(\d+))?$/)&&(!RegExp.$2||0<=RegExp.$3&&128>=RegExp.$3)){var a=RegExp.$1;if("::"==a)return!0;if(0<a.indexOf(".")){var c=a.lastIndexOf(":");if(!c||!cbi_validators.ip4addr.apply(a.substr(c+1)))return!1;a=a.substr(0,c)+":0:0"}if(0<=a.indexOf("::")){for(var c=
0,e="0",d=1;d<a.length-1;d++)":"==a.charAt(d)&&c++;if(7<c)return!1;for(d=0;d<7-c;d++)e+=":0";a.match(/^(.*?)::(.*?)$/)&&(a=(RegExp.$1?RegExp.$1+":":"")+e+(RegExp.$2?":"+RegExp.$2:""))}return null!=a.match(/^(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}$/)}return!1},port:function(){return cbi_validators.integer.apply(this)&&0<=this&&65535>=this},portrange:function(){if(this.match(/^(\d+)-(\d+)$/)){var a=RegExp.$1,c=RegExp.$2;return cbi_validators.port.apply(a)&&cbi_validators.port.apply(c)&&parseInt(a)<=
parseInt(c)}return cbi_validators.port.apply(this)},macaddr:function(){return null!=this.match(/^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$/)},host:function(){return cbi_validators.hostname.apply(this)||cbi_validators.ipaddr.apply(this)},hostname:function(){return 253>=this.length?null!=this.match(/^[a-zA-Z0-9]+$/)||this.match(/^[a-zA-Z0-9_][a-zA-Z0-9_\-.]*[a-zA-Z0-9]$/)&&this.match(/[^0-9.]/):!1},network:function(){return cbi_validators.uciname.apply(this)||cbi_validators.host.apply(this)},wpakey:function(){return 64==
this.length?null!=this.match(/^[a-fA-F0-9]{64}$/):8<=this.length&&63>=this.length},wepkey:function(){var a=this;"s:"==a.substr(0,2)&&(a=a.substr(2));return 10==a.length||26==a.length?null!=a.match(/^[a-fA-F0-9]{10,26}$/):5==a.length||13==a.length},uciname:function(){return null!=this.match(/^[a-zA-Z0-9_]+$/)},range:function(a,c){var e=parseFloat(this);return!isNaN(a)&&!isNaN(c)&&!isNaN(e)?e>=a&&e<=c:!1},min:function(a){var c=parseFloat(this);return!isNaN(a)&&!isNaN(c)?c>=a:!1},max:function(a){var c=
parseFloat(this);return!isNaN(a)&&!isNaN(c)?c<=a:!1},rangelength:function(a,c){var e=""+this;return!isNaN(a)&&!isNaN(c)?e.length>=a&&e.length<=c:!1},minlength:function(a){var c=""+this;return!isNaN(a)?c.length>=a:!1},maxlength:function(a){var c=""+this;return!isNaN(a)?c.length<=a:!1},or:function(){for(var a=0;a<arguments.length;a+=2)if("function"!=typeof arguments[a]){if(arguments[a]==this)return!0;a--}else if(arguments[a].apply(this,arguments[a+1]))return!0;return!1},and:function(){for(var a=0;a<
arguments.length;a+=2)if("function"!=typeof arguments[a]){if(arguments[a]!=this)return!1;a--}else if(!arguments[a].apply(this,arguments[a+1]))return!1;return!0},neg:function(){return cbi_validators.or.apply(this.replace(/^[ \t]*![ \t]*/,""),arguments)},list:function(a,c){if("function"!=typeof a)return!1;for(var e=this.match(/[^ \t]+/g),d=0;d<e.length;d++)if(!a.apply(e[d],c))return!1;return!0},phonedigit:function(){return null!=this.match(/^[0-9\*#!\.]+$/)}};
function cbi_d_add(a,c,e){var d=document.getElementById(a);if(d){for(var g,f=0;f<cbi_d.length;f++)if(cbi_d[f].id==a){g=cbi_d[f];break}g||(g={node:d,id:a,parent:d.parentNode.id,next:e,deps:[]},cbi_d.unshift(g));g.deps.push(c)}}
function cbi_d_checkvalue(a,c){var e=document.getElementById(a),d;if(e)e.value?(d=e.value,"checkbox"==e.type&&(d=e.checked?d:"")):d="";else{e=document.getElementsByName(a);if(0<e.length&&("radio"==e[0].type||"checkbox"==e[0].type))for(var g=0;g<e.length;g++)if(e[g].checked){d=e[g].value;break}d=d?d:""}return d==c}
function cbi_d_check(a){for(var c,e=!1,d=0;d<a.length;d++){var g=!0;c=!1;for(var f in a[d])"!reverse"==f?c=!0:"!default"==f?(e=!0,g=!1):g=g&&cbi_d_checkvalue(f,a[d][f]);if(g)return!c}return e}
function cbi_d_update(){for(var a=!1,c=0;c<cbi_d.length;c++){var e=cbi_d[c],d=document.getElementById(e.next),g=document.getElementById(e.id),f=document.getElementById(e.parent);if(g&&g.parentNode&&!cbi_d_check(e.deps))g.parentNode.removeChild(g),a=!0,e.parent&&cbi_c[e.parent]--;else if((!g||!g.parentNode)&&cbi_d_check(e.deps))d?d.parentNode.insertBefore(e.node,d):f.appendChild(e.node),a=!0,e.parent&&cbi_c[e.parent]++}e&&e.parent&&(cbi_t_update()||cbi_tag_last(f));a&&cbi_d_update()}
function cbi_bind(a,c,e,d){a.addEventListener?a.addEventListener(c,e,!!d):a.attachEvent("on"+c,function(){var a=window.event;!a.target&&a.srcElement&&(a.target=a.srcElement);return!!e(a)});return a}
function cbi_combobox(a,c,e,d){var g="cbi.combobox."+a;if(!document.getElementById(g)){var f=document.getElementById(a),h=document.createElement("select");h.id=g;h.className=f.className.replace(/cbi-input-text/,"cbi-input-select");f.nextSibling?f.parentNode.insertBefore(h,f.nextSibling):f.parentNode.appendChild(h);a=f.getAttribute("cbi_datatype");g=f.getAttribute("cbi_optional");a&&cbi_validate_field(h,"true"==g,a);c[f.value]||(""==f.value?(a=document.createElement("option"),a.value="",a.appendChild(document.createTextNode(e)),
h.appendChild(a)):(e=document.createElement("option"),e.value=f.value,e.selected="selected",e.appendChild(document.createTextNode(f.value)),h.appendChild(e)));for(var p in c)e=document.createElement("option"),e.value=p,f.value==p&&(e.selected="selected"),e.appendChild(document.createTextNode(c[p])),h.appendChild(e);c=document.createElement("option");c.value="";c.appendChild(document.createTextNode(d));h.appendChild(c);f.style.display="none";cbi_bind(h,"change",function(){h.selectedIndex==h.options.length-
1?(f.style.display="inline",h.parentNode.removeChild(h),f.focus()):f.value=h.options[h.selectedIndex].value;try{cbi_d_update()}catch(a){}});h.focus();h.blur()}}function cbi_combobox_init(a,c,e,d){var g=document.getElementById(a);cbi_bind(g,"blur",function(){cbi_combobox(a,c,e,d)});cbi_combobox(a,c,e,d)}function cbi_filebrowser(a,c,e){var d=document.getElementById(a);window.open(c+(d.value||e||"")+"?field="+a,"luci_filebrowser","width=300,height=400,left=100,top=200,scrollbars=yes").focus()}
function cbi_browser_init(a,c,e,d){var g=document.getElementById(a),f=document.createElement("img");f.className="cbi-image-button";f.src=c+"/cbi/folder.gif";g.parentNode.insertBefore(f,g.nextSibling);cbi_bind(f,"click",function(){cbi_filebrowser(a,e,d);return!1})}
function cbi_dynlist_init(a,c,e,d,g){function f(a,f,r){for(k=[];m.firstChild;){var q=m.firstChild,n=parseInt(q.index);n!=r&&("input"==q.nodeName.toLowerCase()?k.push(q.value||""):"select"==q.nodeName.toLowerCase()&&(k[k.length-1]=q.options[q.selectedIndex].value));m.removeChild(q)}0<=f?(a=f+1,k.splice(a,0,"")):0==k.length&&(a=0,k.push(""));for(n=0;n<k.length;n++)f=document.createElement("input"),f.id=s+"."+(n+1),f.name=s,f.value=k[n],f.type="text",f.index=n,f.className="cbi-input-text",0==n&&l&&(f.placeholder=
l),r=document.createElement("img"),r.src=c+(n+1<k.length?"/cbi/remove.gif":"/cbi/add.gif"),r.className="cbi-image-button",m.appendChild(f),m.appendChild(r),m.appendChild(document.createElement("br")),e&&cbi_validate_field(f.id,n+1==k.length||d,e),g?(cbi_combobox_init(f.id,g[0],"",g[1]),f.nextSibling.index=n,cbi_bind(f.nextSibling,"keydown",p),cbi_bind(f.nextSibling,"keypress",h),(n==a||-n==a)&&f.nextSibling.focus()):(cbi_bind(f,"keydown",p),cbi_bind(f,"keypress",h),n==a?f.focus():-n==a&&(f.focus(),
q=f.value,f.value=" ",f.value=q)),cbi_bind(r,"click",u)}function h(a){a=a?a:window.event;var c=a.target?a.target:a.srcElement;3==c.nodeType&&(c=c.parentNode);switch(a.keyCode){case 8:case 46:if(0==c.value.length)return a.preventDefault&&a.preventDefault(),!1;break;case 13:case 38:case 40:return a.preventDefault&&a.preventDefault(),!1}return!0}function p(c){c=c?c:window.event;var d=c.target?c.target:c.srcElement;3==d.nodeType&&(d=d.parentNode);for(var e=d.previousSibling;e&&e.name!=a;)e=e.previousSibling;
for(var g=d.nextSibling;g&&g.name!=a;)g=g.nextSibling;g&&g.nextSibling.name==a&&(g=g.nextSibling);switch(c.keyCode){case 8:case 46:if("select"==d.nodeName.toLowerCase()||0==d.value.length)return c.preventDefault&&c.preventDefault(),e=d.index,8==c.keyCode&&(e=-e+1),f(e,-1,d.index),!1;break;case 13:f(-1,d.index,-1);break;case 38:e&&e.focus();break;case 40:g&&g.focus()}return!0}function u(a){a=a?a:window.event;a=a.target?a.target:a.srcElement;-1<a.src.indexOf("remove")?(a.previousSibling.value="",p({target:a.previousSibling,
keyCode:8})):p({target:a.previousSibling,keyCode:13});return!1}var t=document.getElementsByName(a)[0],s=t.name,m=t.parentNode,l=t.placeholder,k;f(NaN,-1,-1)}function cbi_hijack_forms(a,c,e,d){a=a.getElementsByTagName("form");for(var g=0;g<a.length;g++)$(a[g]).observe("submit",function(a){a.stop();a.element().request({onSuccess:c,onFailure:e});d&&d()})}
function cbi_t_add(a,c){var e=document.getElementById("tab."+a+"."+c),d=document.getElementById("container."+a+"."+c);e&&d&&(cbi_t[a]=cbi_t[a]||[],cbi_t[a][c]={tab:e,container:d,cid:d.id})}
function cbi_t_switch(a,c){if(cbi_t[a]&&cbi_t[a][c]){var e=cbi_t[a][c],d=document.getElementById("tab."+a),g;for(g in cbi_t[a]){var f=cbi_t[a][g];e.tab.id!=f.tab.id?(f.tab.className=f.tab.className.replace(/(^| )cbi-tab( |$)/," cbi-tab-disabled "),f.container.style.display="none"):(d&&(d.value=c),f.tab.className=f.tab.className.replace(/(^| )cbi-tab-disabled( |$)/," cbi-tab "),f.container.style.display="block")}}return!1}
function cbi_t_update(){var a=[],c=!1,e;for(e in cbi_t)for(var d in cbi_t[e])0==cbi_c[cbi_t[e][d].cid]?cbi_t[e][d].tab.style.display="none":cbi_t[e][d].tab&&"none"==cbi_t[e][d].tab.style.display&&(cbi_t[e][d].tab.style.display="",c=cbi_t[e][d].tab,c.className+=" cbi-tab-highlighted",a.push(c)),cbi_tag_last(cbi_t[e][d].container),c=!0;0<a.length&&window.setTimeout(function(){for(var c=0;c<a.length;c++)a[c].className=a[c].className.replace(/ cbi-tab-highlighted/g,"")},750);return c}
function cbi_validate_form(a,c){if("add-section"==a.cbi_state||"del-section"==a.cbi_state)return!0;if(a.cbi_validators)for(var e=0;e<a.cbi_validators.length;e++)if(!(0,a.cbi_validators[e])()&&c)return alert(c),!1;return!0}function cbi_validate_reset(a){window.setTimeout(function(){cbi_validate_form(a,null)},100);return!0}
function cbi_validate_compile(a){var c=0,e=!1,d=0,g=[];a+=",";for(var f=0;f<a.length;f++)if(e)e=!1;else switch(a.charCodeAt(f)){case 92:e=!0;break;case 40:case 44:if(0>=d){if(c<f)if(c=a.substring(c,f),c=c.replace(/\\(.)/g,"$1"),c=c.replace(/^[ \t]+/g,""),(c=c.replace(/[ \t]+$/g,""))&&!isNaN(c))g.push(parseFloat(c));else if(c.match(/^(['"]).*\1$/))g.push(c.replace(/^(['"])(.*)\1$/,"$2"));else if("function"==typeof cbi_validators[c])g.push(cbi_validators[c]),g.push(null);else throw"Syntax error, unhandled token '"+
c+"'";c=f+1}d+=40==a.charCodeAt(f);break;case 41:if(0>=--d){if("function"!=typeof g[g.length-2])throw"Syntax error, argument list follows non-function";g[g.length-1]=arguments.callee(a.substring(c,f));c=f+1}}return g}
function cbi_validate_field(a,c,e){var d="string"==typeof a?document.getElementById(a):a,g;try{g=cbi_validate_compile(e)}catch(f){}d&&(g&&"function"==typeof g[0])&&(a=function(){if(d.form){d.className=d.className.replace(/ cbi-input-invalid/g,"");var a=d.options&&-1<d.options.selectedIndex?d.options[d.options.selectedIndex].value:d.value;if(!(0==a.length&&c||g[0].apply(a,g[1])))return d.className+=" cbi-input-invalid",!1}return!0},d.form.cbi_validators||(d.form.cbi_validators=[]),d.form.cbi_validators.push(a),
cbi_bind(d,"blur",a),cbi_bind(d,"keyup",a),"SELECT"==d.nodeName&&(cbi_bind(d,"change",a),cbi_bind(d,"click",a)),d.setAttribute("cbi_validate",a),d.setAttribute("cbi_datatype",e),d.setAttribute("cbi_optional",(!!c).toString()),a(),(a=document.getElementById("cbi.combobox."+d.id))&&cbi_validate_field(a,c,e))}
function cbi_row_swap(a,c,e){for(var d=a.parentNode;d&&"tr"!=d.nodeName.toLowerCase();)d=d.parentNode;if(!d)return!1;for(a=d.parentNode;a&&"table"!=a.nodeName.toLowerCase();)a=a.parentNode;if(!a)return!1;for(var g=c?a.rows.length:a.rows.length-1,f=c?3:2;f<g;f++)if(a.rows[f]==d){c?d.parentNode.insertBefore(a.rows[f],a.rows[f-1]):d.parentNode.insertBefore(a.rows[f+1],a.rows[f]);break}c=[];for(f=2;f<a.rows.length;f++)a.rows[f].className=a.rows[f].className.replace(/cbi-rowstyle-[12]/,"cbi-rowstyle-"+
(1+f%2)),a.rows[f].id&&a.rows[f].id.match(/-([^\-]+)$/)&&c.push(RegExp.$1);if(e=document.getElementById(e))e.value=c.join(" ");return!1}function cbi_tag_last(a){for(var c,e=0;e<a.childNodes.length;e++){var d=a.childNodes[e];1==d.nodeType&&"div"==d.nodeName.toLowerCase()&&(d.className=d.className.replace(/ cbi-value-last$/,""),c=d)}c&&(c.className+=" cbi-value-last")}
String.prototype.serialize=function(){switch(typeof this){case "object":if(null==this)return"null";if(this.length){var a,c="";for(a=0;a<this.length;a++)c+=(c?", ":"")+String.serialize(this[a]);return"[ "+c+" ]"}c="";for(a in this)c+=(c?", ":"")+a+": "+String.serialize(this[a]);return"{ "+c+" }";case "string":return this.match(/[^a-zA-Z0-9_,.: -]/)?'decodeURIComponent("'+encodeURIComponent(this)+'")':'"'+this+'"';default:return this.toString()}};
String.prototype.format=function(){function a(a,c){for(var d=0;d<c.length;d+=2)a=a.replace(c[d],c[d+1]);return a}if(RegExp){for(var c=[/&/g,"&#38;",/"/g,"&#34;",/'/g,"&#39;",/</g,"&#60;",/>/g,"&#62;"],e=[/"/g,"&#34;",/'/g,"&#39;"],d=this,g="",f=/^(([^%]*)%('.|0|\x20)?(-)?(\d+)?(\.\d+)?(%|b|c|d|u|f|o|s|x|X|q|h|j|t|m))/,h=b=[],p=0,u=0;h=f.exec(d);){var t=h[1],s=h[2],m=h[3],l=h[5],k=h[6],v=h[7];u++;if("%"==v)j="%";else if(p<arguments.length){h=arguments[p++];m&&"'"==m.substr(0,1)&&s.substr(1,1);l&&parseInt(l);
m=-1;k&&"f"==v&&(m=parseInt(k.substring(1)));var j=h;switch(v){case "b":j=(parseInt(h)||0).toString(2);break;case "c":j=String.fromCharCode(parseInt(h)||0);break;case "d":j=parseInt(h)||0;break;case "u":j=Math.abs(parseInt(h)||0);break;case "f":j=-1<m?(parseFloat(h)||0).toFixed(m):parseFloat(h)||0;break;case "o":j=(parseInt(h)||0).toString(8);break;case "s":j=h;break;case "x":j=(""+(parseInt(h)||0).toString(16)).toLowerCase();break;case "X":j=(""+(parseInt(h)||0).toString(16)).toUpperCase();break;
case "h":j=a(h,c);break;case "q":j=a(h,e);break;case "j":j=String.serialize(h);break;case "t":j=l=k=0;h=h||0;60<h&&(j=Math.floor(h/60),h%=60);60<j&&(l=Math.floor(j/60),j%=60);24<l&&(k=Math.floor(l/24),l%=24);j=0<k?String.format("%dd %dh %dm %ds",k,l,j,h):String.format("%dh %dm %ds",l,j,h);break;case "m":l=l?parseInt(l):1E3;k=k?Math.floor(10*parseFloat("0"+k)):2;j=0;h=parseFloat(h||0);m=" K M G T P E".split(" ");for(j=0;j<m.length&&h>l;j++)h/=l;j=h.toFixed(k)+" "+m[j]}}g+=s+j;d=d.substr(t.length)}return g+
d}};String.prototype.nobr=function(){return this.replace(/[\s\n]+/g,"&#160;")};String.serialize=function(){for(var a=[],c=1;c<arguments.length;c++)a.push(arguments[c]);return"".serialize.apply(arguments[0],a)};String.format=function(){for(var a=[],c=1;c<arguments.length;c++)a.push(arguments[c]);return"".format.apply(arguments[0],a)};String.nobr=function(){for(var a=[],c=1;c<arguments.length;c++)a.push(arguments[c]);return"".nobr.apply(arguments[0],a)};
